name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-analysis:
    runs-on: [self-hosted, linux]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby (for Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Jekyll and Dependencies
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build the Jekyll site
        run: |
          bundle exec jekyll build

      - name: Set up SonarQube Scanner
        run: |
          # Download and install the SonarScanner if it's not installed yet
          wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.7.0.2747/sonar-scanner-4.7.0.2747-linux.zip
          unzip sonar-scanner-4.7.0.2747-linux.zip
          export PATH=$PWD/sonar-scanner-4.7.0.2747-linux/bin:$PATH
          sonar-scanner --version

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner
