name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-analysis:
    runs-on: [self-hosted, linux, jekyll]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Jekyll and Dependencies
        run: |
          bundle install

      - name: Build the Jekyll site
        run: |
          bundle exec jekyll build

      - name: SonarQube Analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Digital-CV \
            -Dsonar.projectName=Digital-CV \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=_site \
            -Dsonar.host.url=http://analysis.mathijsnabbe.nl \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
            -Dsonar.pullrequest.branch=${{ github.head_ref }} \
            -Dsonar.pullrequest.base=${{ github.base_ref }}
